### ISSUE TITLE
样式覆盖问题

### ISSUE THREAD

**Issue by Tomaolala** [chen-mou/online_blackboard#2]
![image](https://user-images.githubusercontent.com/76248720/198837059-4955b5fc-79cd-4114-a875-1bfc42ea4f92.png)

![image](https://user-images.githubusercontent.com/76248720/198836879-00db87f3-42be-4755-8501-d554702498bb.png)
这个margin-top影响到了右边子组件的样式

**Comment by Tomaolala** [comment]
@ChenzDNA 我注释了

**Comment by ZhengDNA** [comment]
那就改成padding-top

**Comment by Tomaolala** [comment]
ok


> 那就改成padding-top
1
